version: '3.3'
services:
  real-estate-backend:
    build:
      context: estate
      dockerfile: Dockerfile
    image: real-estate-backend:latest
    ports:
      - 8080:8080
  database:
    image: postgres:13
    ports:
      - "5432:54323"
#  real-estate-ui:
#    build:
#      context: real-estate-web-ui
#      dockerfile: Dockerfile
#    image: real-estate-ui:latest
#    ports:
#      - 4200:4200
